"""empty message

Revision ID: 010facbe4c55
Revises: f3a9bf416eae
Create Date: 2021-08-01 16:10:18.315448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010facbe4c55'
down_revision = 'f3a9bf416eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.drop_index('ix_job_posting_contact_phone')
        batch_op.drop_index('ix_job_posting_location')
        batch_op.drop_index('ix_job_posting_physical_address')
        batch_op.drop_index('ix_job_posting_position_title')
        batch_op.drop_index('ix_job_posting_timestamp')

    op.drop_table('job_posting')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('resume')

    op.create_table('job_posting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('position_title', sa.VARCHAR(length=30), nullable=True),
    sa.Column('location', sa.VARCHAR(length=30), nullable=True),
    sa.Column('contact_phone', sa.INTEGER(), nullable=True),
    sa.Column('physical_address', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.create_index('ix_job_posting_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_job_posting_position_title', ['position_title'], unique=False)
        batch_op.create_index('ix_job_posting_physical_address', ['physical_address'], unique=False)
        batch_op.create_index('ix_job_posting_location', ['location'], unique=False)
        batch_op.create_index('ix_job_posting_contact_phone', ['contact_phone'], unique=False)

    # ### end Alembic commands ###
