"""empty message

Revision ID: 407f4624974b
Revises: 010facbe4c55
Create Date: 2021-08-01 19:11:05.948878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407f4624974b'
down_revision = '010facbe4c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_path', sa.String(length=120), nullable=True))
        batch_op.drop_column('resume')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('resume_path')

    # ### end Alembic commands ###
