"""job posting changes - deleted location, expanded body

Revision ID: b67c70f9dbd3
Revises: 8541f87f3c07
Create Date: 2021-08-05 12:18:05.516135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67c70f9dbd3'
down_revision = '8541f87f3c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_location')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=30), nullable=True))
        batch_op.create_index('ix_post_location', ['location'], unique=False)

    # ### end Alembic commands ###
