"""users table

Revision ID: db0b5956107d
Revises: 
Create Date: 2021-07-17 20:51:59.742333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0b5956107d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('number_jobs', sa.Integer(), nullable=True),
    sa.Column('home_address', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.Integer(), nullable=True),
    sa.Column('date_birth', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_contact_phone'), 'employees', ['contact_phone'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_home_address'), 'employees', ['home_address'], unique=False)
    op.create_index(op.f('ix_employees_location'), 'employees', ['location'], unique=False)
    op.create_index(op.f('ix_employees_number_jobs'), 'employees', ['number_jobs'], unique=False)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    op.create_table('employers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('legal_person_name', sa.String(length=10), nullable=True),
    sa.Column('legal_person_phone', sa.Integer(), nullable=True),
    sa.Column('contact_phone', sa.Integer(), nullable=True),
    sa.Column('physical_address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employers_contact_phone'), 'employers', ['contact_phone'], unique=False)
    op.create_index(op.f('ix_employers_email'), 'employers', ['email'], unique=True)
    op.create_index(op.f('ix_employers_legal_person_name'), 'employers', ['legal_person_name'], unique=False)
    op.create_index(op.f('ix_employers_legal_person_phone'), 'employers', ['legal_person_phone'], unique=False)
    op.create_index(op.f('ix_employers_physical_address'), 'employers', ['physical_address'], unique=False)
    op.create_index(op.f('ix_employers_username'), 'employers', ['username'], unique=True)
    op.create_table('job-postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_title', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('contact_phone', sa.Integer(), nullable=True),
    sa.Column('physical_address', sa.String(length=100), nullable=True),
    sa.Column('date_posted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job-postings_contact_phone'), 'job-postings', ['contact_phone'], unique=False)
    op.create_index(op.f('ix_job-postings_date_posted'), 'job-postings', ['date_posted'], unique=False)
    op.create_index(op.f('ix_job-postings_location'), 'job-postings', ['location'], unique=False)
    op.create_index(op.f('ix_job-postings_physical_address'), 'job-postings', ['physical_address'], unique=False)
    op.create_index(op.f('ix_job-postings_position_title'), 'job-postings', ['position_title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job-postings_position_title'), table_name='job-postings')
    op.drop_index(op.f('ix_job-postings_physical_address'), table_name='job-postings')
    op.drop_index(op.f('ix_job-postings_location'), table_name='job-postings')
    op.drop_index(op.f('ix_job-postings_date_posted'), table_name='job-postings')
    op.drop_index(op.f('ix_job-postings_contact_phone'), table_name='job-postings')
    op.drop_table('job-postings')
    op.drop_index(op.f('ix_employers_username'), table_name='employers')
    op.drop_index(op.f('ix_employers_physical_address'), table_name='employers')
    op.drop_index(op.f('ix_employers_legal_person_phone'), table_name='employers')
    op.drop_index(op.f('ix_employers_legal_person_name'), table_name='employers')
    op.drop_index(op.f('ix_employers_email'), table_name='employers')
    op.drop_index(op.f('ix_employers_contact_phone'), table_name='employers')
    op.drop_table('employers')
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_number_jobs'), table_name='employees')
    op.drop_index(op.f('ix_employees_location'), table_name='employees')
    op.drop_index(op.f('ix_employees_home_address'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_contact_phone'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
