"""empty message

Revision ID: fff6d3295e9c
Revises: b51a4744b93c
Create Date: 2021-08-08 16:01:44.805702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff6d3295e9c'
down_revision = 'b51a4744b93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'])

    # ### end Alembic commands ###
